import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Generates a Context Map (Agent.md) for AI agents
 * Maps the file structure so AI tools have accurate project context
 */
export async function generateContextMap() {
    const workspaceFolders = vscode.workspace.workspaceFolders;

    if (!workspaceFolders || workspaceFolders.length === 0) {
        vscode.window.showErrorMessage('No workspace folder is open!');
        return;
    }

    const workspaceRoot = workspaceFolders[0].uri.fsPath;
    const agentFilePath = path.join(workspaceRoot, 'Agent.md');

    try {
        await vscode.window.withProgress(
            {
                location: vscode.ProgressLocation.Notification,
                title: 'Generating Context Map...',
                cancellable: false,
            },
            async () => {
                const fileTree = await buildFileTree(workspaceRoot);
                const content = formatContextMap(fileTree, workspaceRoot);

                fs.writeFileSync(agentFilePath, content, 'utf8');
            }
        );

        vscode.window.showInformationMessage(
            '✓ Context Map generated successfully! Check Agent.md'
        );

        // Open the generated file
        const doc = await vscode.workspace.openTextDocument(agentFilePath);
        await vscode.window.showTextDocument(doc);
    } catch (error) {
        vscode.window.showErrorMessage(
            `Failed to generate Context Map: ${error}`
        );
    }
}

/**
 * Builds a file tree structure recursively
 */
async function buildFileTree(
    dir: string,
    depth: number = 0,
    maxDepth: number = 5
): Promise<string[]> {
    if (depth > maxDepth) {
        return [];
    }

    const entries: string[] = [];
    const items = fs.readdirSync(dir, { withFileTypes: true });

    // Filter out common directories to ignore
    const ignoreList = ['node_modules', '.git', 'out', 'dist', '.vscode-test'];

    for (const item of items) {
        if (ignoreList.includes(item.name)) {
            continue;
        }

        const indent = '  '.repeat(depth);
        const itemPath = path.join(dir, item.name);

        if (item.isDirectory()) {
            entries.push(`${indent}📁 ${item.name}/`);
            const subEntries = await buildFileTree(itemPath, depth + 1, maxDepth);
            entries.push(...subEntries);
        } else {
            entries.push(`${indent}📄 ${item.name}`);
        }
    }

    return entries;
}

/**
 * Formats the file tree into a markdown document
 */
function formatContextMap(fileTree: string[], workspaceRoot: string): string {
    const projectName = path.basename(workspaceRoot);
    const timestamp = new Date().toISOString().split('T')[0];

    return `# Project Context Map
**Generated by PCW ToolBelt**  
**Project:** ${projectName}  
**Date:** ${timestamp}

---

## File Structure

\`\`\`
${fileTree.join('\n')}
\`\`\`

---

## Project Guardrails

*Define your coding rules here for AI agents:*

- **Naming Convention:** camelCase for JavaScript/TypeScript, snake_case for PHP
- **Strict Types:** Always use TypeScript strict mode
- **No Inline CSS:** Extract to separate style definitions
- **Sanitization Required:** All user inputs must be sanitized

---

## Notes

This context map helps AI tools understand your project structure and avoid hallucinating incorrect paths.

Update this file when your structure changes using: \`PCW: Update Guardrails\`
`;
}
